spring:
  application:
    name: cloud-aws
  cloud:
    aws:
      region:
        static: {region}
      credentials:
        access-key:
        secret-key:
      s3:
        endpoint: https://{namespace}.compat.objectstorage.{region}.oraclecloud.com
        path-style-access-enabled: true
