management:
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  application:
    name: spring-ai
  ai:
    openai:
      api-key: ${openaiApiKey}
      chat:
        options:
          model: gpt-4o-mini # default
          temperature: 0.7 # default
      embedding:
        options:
          model: text-embedding-3-large # default, text-embedding-ada-002

#    chat:
#      client:
#        observations:
#          log-prompt: true # user, system 입력한 내용만 보이고 전체 내용은 안보임
#      observations:
#        log-prompt: true # Chat 모델 프롬프트 전체가 보임

logging:
  level:
    "[org.springframework.ai.chat.client.advisor.SimpleLoggerAdvisor]": debug
