management:
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  application:
    name: spring-ai

  servlet:
    multipart:
      max-request-size: -1
      max-file-size: -1

  ai:
    model:
      chat: ollama
      embedding: ollama

    openai:
      api-key: ${openaiApiKey}
      chat:
        options:
          model: gpt-4o-mini # default
          temperature: 0.7 # default
      embedding:
        options:
          model: text-embedding-3-large # default, text-embedding-ada-002

    ollama:
      base-url: http://10.32.3.155:11434
      chat:
        model: qwen2.5-coder:14b # default mistral
        options:
          temperature: 0.8 # default
      embedding:
        model: mxbai-embed-large # default

    vectorstore:
      chroma:
        client:
          host: http://localhost # default
          port: 8000 # default
        initialize-schema: false # default
        tenant-name: SpringAiTenant # default
        database-name: SpringAiDatabase # default
        collection-name: SpringAiCollection # default

#    chat:
#      client:
#        observations:
#          log-prompt: true # user, system 입력한 내용만 보이고 전체 내용은 안보임
#      observations:
#        log-prompt: true # Chat 모델 프롬프트 전체가 보임

logging:
  level:
    "[org.springframework.ai.chat.client.advisor.SimpleLoggerAdvisor]": debug
