spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jpa_test?createDatabaseIfNotExist=true
    username: root
    password: 111111

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        jdbc:
          batch_size: 100
        show_sql: false
        format_sql: true
    open-in-view: false
    defer-datasource-initialization: true

logging:
  level:
    "[com.ask]": debug
    "[org.hibernate.SQL]": debug
    "[org.hibernate.orm.jdbc.bind]": trace
