spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jpa_test?createDatabaseIfNotExist=true&rewriteBatchedStatements=true
    username: root
    password: 111111

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      "[hibernate.show_sql]": false
      "[hibernate.format_sql]": true
      "[hibernate.jdbc.batch_size]": 100
      "[hibernate.order_inserts]": true
      "[hibernate.order_updates]": true
      "[hibernate.default_batch_fetch_size]": 50
      "[hibernate.query.in_clause_parameter_padding]": true
    open-in-view: false
    defer-datasource-initialization: true

logging:
  level:
    "[com.ask]": debug
    "[org.hibernate.SQL]": debug
    "[org.hibernate.orm.jdbc.bind]": trace
