spring:
  application:
    name: resilience4j

management:
  health:
    circuitbreakers:
      enabled: true
    ratelimiters:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

resilience4j:
  circuitbreaker:
    configs:
      default:
        register-health-indicator: true
    instances:
      google:
        base-config: default
  ratelimiter:
    configs:
      default:
        register-health-indicator: true
        limit-for-period: 5
        limit-refresh-period: 5s
        timeout-duration: 0s
    instances:
      google:
        base-config: default
