spring:
  datasource:
    url: jdbc:h2:mem:test;DB_CLOSE_ON_EXIT=FALSE
    username: sa

  jpa:
    properties:
      hibernate:
        show_sql: false
        format_sql: true
    open-in-view: false
    defer-datasource-initialization: true
  jackson:
    deserialization:
      read-date-timestamps-as-nanoseconds: false
  task:
    scheduling:
      pool:
        size: 5

    execution:
      thread-name-prefix: async-
      pool:
        core-size: 20

  http:
    client:
      read-timeout: 30s
      connect-timeout: 3s

core:
  project-version: ${version}

logging:
  pattern:
    dateformat: yyyy-MM-dd HH:mm:ss.SSS
