spring:
  datasource:
    url: jdbc:h2:mem:test;DB_CLOSE_ON_EXIT=FALSE
    username: sa

  jpa:
    properties:
      hibernate:
        show_sql: false
        format_sql: true
    open-in-view: false
    defer-datasource-initialization: true

core:
  project-version: ${version}

logging:
  pattern:
    dateformat: yyyy-MM-dd HH:mm:ss.SSS
