spring:
  application:
    name: redis-app
  threads:
    virtual:
      enabled: true
  data:
    redis:
      sentinel:
        master: mymaster
        nodes: localhost:26379,localhost:26380,localhost:26381

logging:
  level:
    "[com.ask]": debug
    "[org.redisson.command.RedisExecutor]": debug
